version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python -m pip install --upgrade --no-cache-dir pip-tools
      - pip-compile --extra doc --output-file=docs/requirements.txt pyproject.toml
      - python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
      - echo a_fake_api_key > api_key

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
