name: OpenBusAPI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    environment: "OpenBusEnvironment"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Summary
      id: strings
      shell: bash
      run: |
        echo "Operating system=${{matrix.os}}"
        echo "Python Version=${{matrix.python-version}}"

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{matrix.python-version}}

    - name: Setup dependencies
      run: uv sync --dev

    - name: Run tests
      env:
        OPEN_BUS_API_KEY: ${{secrets.OPEN_BUS_API_KEY}}
      run: uv run --frozen pytest

    - name: Lint with ruff
      run: uv run ruff check

    - name: Get Coverage
      env:
        OPEN_BUS_API_KEY: ${{secrets.OPEN_BUS_API_KEY}}
      run: |
        source .venv/bin/activate
        coverage run -m pytest
        coverage xml

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
